### PR TITLE
+py3k compat

### PR DESCRIPTION
**Pull request by xantares**

### CODE REVIEW

**Comment by fiatjaf** [comment]
Do you really have this working? I tried it many years ago but got this problem: https://github.com/luksan/pyfprint/issues/2

So I resorted to using the original library in C.

**Comment by luksan** [comment]
Sorry, the last commit I made to this codebase was 6 months before Python 3.0 was released..

I haven't written any code for fingerprint devices since then.

**Comment by xantares** [comment]
@fiatjaf, yes that PR got it totally working (it contains fixes)

**Comment by xantares** [comment]
please merge

**Comment by Carloos09** [comment]
hi, i'm using pyfprint.
somebody tell me how to save fingerprints in bd MySQL and use discover_prints for verification?
thank you

**Comment by fiatjaf** [comment]
@Carloos09 The simplest solution is to encode them to base64 and save that (a string) to the database. When you're trying to `discover_prints` you must have previously loaded all the prints from the database and passed them to the library.

**Comment by Carloos09** [comment]
sorry, I'm new to python code.
you could tell me how to do it, my confusion is because using save_to_disk says "finger is a member of Fingers, indicating which finger this is." and I need to store more fingerprints than those available on Fingers.

**Comment by fiatjaf** [comment]
@Carloos09 ignore that, it is for the case when you're storing multiple fingers of the same person, I don't know how it goes, but maybe it will store everything in one file.

I guess what you want is to call [`.data()`](https://github.com/luksan/pyfprint/blob/9e579e237ce73108c11acfc9703e382128696bf6/pyfprint/pyfprint.py#L547-L558) to get a binary representation of a fingerprint, then you can base64 encode this and save in a database.

Later, when you want to identify a fingerprint, you'll have a `Device` object handling the fingerprint reader, then you must load all the fingerprints from the database, instantiate a `FPrint` with the binary data, pass it to [`device.verify_finger()`](https://github.com/luksan/pyfprint/blob/9e579e237ce73108c11acfc9703e382128696bf6/pyfprint/pyfprint.py#L547-L558) and see if it matches. If yes then you've identified the person, otherwise proceed, if none match then the person is a stranger.

**Comment by Carloos09** [comment]
thank you very much giovanni, I had already thought of it that way and it worked for me. I guess to pass all fingerprints by verify () I will have to create a loop. I ask you according to your experience, maximum how many fingerprints I can have in the database before the system slows down when I want to perform a verify () to find a person ?.

El 21 oct. 2017 12:49 PM, "Giovanni T. Parra" <notifications@github.com> escribió:

@Carloos09<https://github.com/carloos09> ignore that, it is for the case when you're storing multiple fingers of the same person, I don't know how it goes, but maybe it will store everything in one file.

I guess what you want is to call .data()<https://github.com/luksan/pyfprint/blob/9e579e237ce73108c11acfc9703e382128696bf6/pyfprint/pyfprint.py#L547-L558> to get a binary representation of a fingerprint, then you can base64 encode this and save in a database.

Later, when you want to identify a fingerprint, you'll have a Device object handling the fingerprint reader, then you must load all the fingerprints from the database, instantiate a FPrint with the binary data, pass it to device.verify_finger()<https://github.com/luksan/pyfprint/blob/9e579e237ce73108c11acfc9703e382128696bf6/pyfprint/pyfprint.py#L547-L558> and see if it matches. If yes then you've identified the person, otherwise proceed, if none match then the person is a stranger.

**Comment by fiatjaf** [comment]
I'm not the best person to provide you with that kind of information, but I guess you can see how much memory does a fingerprint binary occupies (if you're saving it to disk or to the database you can get the information from these sources -- it would be better to get the size of the `Fprint` Python object itself, but I don't know if it will be possible), then compare that with the amount of RAM memory you have available. The library should add some overhead, so double the size, just in case.

It should be able to handle a lot.

Are you seeing any memory leak warnings? These are not good.

Also, I remember trying to use this library with over 50 fingerprints, and it got a little too slow (the iteration process of trying each fingerprint), if I remember well. It's probably faster to use the C library directly. How many fingerprints are you thinking about storing?

---

About the slowness, if you find it -- it solves the problem if instead of trying all stored fingerprints for each person that arrives you somehow identify them before: let the person type their id, for example, then just check the fingerprint for that given id against the person's finger.

**Comment by Carloos09** [comment]
ok giovanni thank you very much for the advice. Regarding memory leakage when wrapping a fingerprint, do you know why this happens? do you know how to solve it? what consequences does this have?

El 21 oct. 2017 1:12 PM, "Giovanni T. Parra" <notifications@github.com> escribió:

I'm not the best person to provide you with that kind of information, but I guess you can see how much memory does a fingerprint binary occupies (if you're saving it to disk or to the database you can get the information from these sources -- it would be better to get the size of the Fprint Python object itself, but I don't know if it will be possible), then compare that with the amount of RAM memory you have available. The library should add some overhead, so double the size, just in case.

It should be able to handle a lot.

Are you seeing any memory leak warnings? These are not good.

Also, I remember trying to use this library with over 50 fingerprints, and it got a little too slow (the iteration process of trying each fingerprint), if I remember well. It's probably faster to use the C library directly. How many fingerprints are you thinking about storing?

________________________________

About the slowness, if you find it -- it solves the problem if instead of trying all stored fingerprints for each person that arrives you somehow identify them before: let the person type their id, for example, then just check the fingerprint for that given id against the person's finger.

**Comment by Carloos09** [comment]
Hello!!
can anyone help me please?
i want know how to use def identify_finger(self, fprints).
i have some .txt of fprints but i don't know how to convert that to a list of Fprints and use def identify_finger(self, fprints).

**Pull request merged**
